[package]
name = "vls-protocol-signer"
version = "0.1.0"
authors = ["Devrandom <c1.devrandom@niftybox.net>"]
edition = "2018"

[features]
default = ["std"]
no-std = ["lightning-signer-core/no-std"]
std = ["vls-protocol/std", "lightning-signer-core/std"]
secp-lowmemory = ["lightning-signer-core/secp-lowmemory"]
use_backtrace = ["lightning-signer-core/use_backtrace"]

[dependencies]
vls-protocol = { path = "../vls-protocol" }
log = { version = "0.4", default_features = false }
serde = { version = "1.0", default_features = false }
bit-vec = { version = "0.6", default_features = false }

[dependencies.lightning-signer-core]
path = "../lightning-signer-core"
default_features = false

