[package]
name = "vlsd"
version = "0.1.0-5"
authors = ["Devrandom <c1.devrandom@niftybox.net>", "Ken Sedgwick <ken@bonsai.com>"]
edition = "2018"
license = "Apache-2.0"
description = "vlsd and vls-cli binaries."
homepage = "https://gitlab.com/lightning-signer/docs/"
repository = "https://gitlab.com/lightning-signer/validating-lightning-signer"
readme = "../README.md"
rust-version = "1.60.0"

[features]
default = ["debug", "frontend"]
test_utils = ["lightning-signer-core/test_utils"]
frontend = ["vls-frontend"]
debug = ["log_pretty_print"]
log_pretty_print = []

[dependencies]
anyhow = "1.0"
log = { version="0.4.14", features = [ "std" ] }
time = "0.2"
lightning-signer-core = { path = "../lightning-signer-core", features = ["debug", "grpc", "use_backtrace"] }
lightning-signer-server = { path = "../lightning-signer-server", features = ["persist", "grpc", "persist-kv-json", "frontend"] }
vls-protocol-signer = { path = "../vls-protocol-signer" }
vls-frontend = { path = "../vls-frontend", optional = true }
bitcoind-client = { path = "../bitcoind-client" }
backtrace = "0.3"
bip39 = { version = "1.0.0", features = ["rand"] }
hex = "0.4"
kv = { version = "0.23", features = ["json-value"] }
tonic = { version = "0.6" }
prost = { version = "0.9" }
tokio = { version = "1.17", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
clap = { version = "=3.0.0-beta.2" }
ctrlc = { version = "3.1.9", features = ["termination"] }
triggered = "0.1.1"
tracing = { version = "0.1.32" }
tracing-subscriber = { version = "0.3.9" }
async-trait = "0.1"

url = { version = "2.2" }

# For logging in unit tests
test-log = "0.2.8"
env_logger = "0.9.0"

[build-dependencies]
tonic-build = "0.6"

[[bin]]
name = "vls-cli"
path = "src/client_main.rs"

[[bin]]
name = "vlsd"
path = "src/server_main.rs"

# TODO fix this test
#[[bin]]
#name = "chain_test"
#path = "src/chain_test_main.rs"
