cache:
  key: "17"
  paths:
    - subprojects/packagecache/

image: greenaddress/ci@sha256:e7ba24b0b73d550842994306bb09df2edba0791223e783dfd09a2acb42694296

stages:
  - format
  - build
  - test
  - deploy
  - publish

.ndk_release:
  tags:
    - ga
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-android-jni

.osx_test:
  tags:
    - osx
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - subprojects/packagecache/

.py_release:
  tags:
    - ga
  before_script:
    - mkdir $CI_PROJECT_DIR/gdk-python
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-python

.ios_release:
  extends: .osx_test
  when: manual # TODO remove
  before_script:
    - mkdir $CI_PROJECT_DIR/gdk-iphone
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-iphone

.ios_sim_release:
  extends: .osx_test
  when: manual # TODO remove
  before_script:
    - mkdir $CI_PROJECT_DIR/gdk-iphone-sim
    - cargo --version # TODO remove
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 1 day
    when: on_success
    paths:
    - gdk-iphone-sim

test_format:
  tags:
    - ga
  stage: format
  script:
    - ./tools/format.sh && git diff --exit-code

release_py3m_bullseye:
  extends: .py_release
  script:
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-python --gcc --python-version 3.9 --external-deps-dir /prebld/gcc

release_py3m_bullseye_debug:
  extends: .py_release
  when: manual
  script:
    - NUM_JOBS=16 ./tools/build.sh --buildtype=debug --install $PWD/gdk-python --gcc --python-version 3.9 --external-deps-dir /prebld/gcc

release_py3m_ubuntu_18.04:
  image: greenaddress/ubuntu_ci@sha256:44146516560880da9e33546706f07a2b99efd6248f6129bfef980472eefe3786
  extends: .py_release
  script:
    - apt-get update -y
    - apt-get install -y cmake
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-python --gcc --python-version 3.6

release_py3m_osx:
  extends: .py_release
  when: manual # TODO remove
  tags:
    - osx-ia
  script:
    - cargo --version # TODO remove
    - cd $CI_PROJECT_DIR
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-python --clang --python-version 3.9

release_py3m_osx_m1:
  extends: .py_release
  when: manual # TODO remove
  tags:
    - osx-m1
  script:
    - cargo --version # TODO remove
    - cd $CI_PROJECT_DIR
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-python --clang --python-version 3.9

test_fedora_clang:
  image: greenaddress/fedora_ci@sha256:72f5371e7da9c0659430ac07f3085fd49ec7e6788ecfd664f4a34b530bc0ff8b
  tags:
    - ga
  script:
    - yum install -y cmake
    - python3 -m pip install virtualenv
    - python3 -m virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --clang

test_clang:
  tags:
    - ga
  script:
    - NUM_JOBS=16 ./tools/build.sh --clang --enable-tests --external-deps-dir /prebld/clang # REVERTME
    - ./build-clang/test_aes_gcm >/dev/null
    - ./build-clang/test_json
    - ./build-clang/test_networks

gdk_clang_ndk_armeabi-v7a:
  extends: .ndk_release
  when: manual # TODO remove
  script:
    - mkdir gdk-android-jni
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-android-jni --ndk armeabi-v7a --external-deps-dir /prebld/armv7a

gdk_clang_ndk_arm64-v8a:
  extends: .ndk_release
  script:
    - mkdir gdk-android-jni
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-android-jni --ndk arm64-v8a --external-deps-dir /prebld/armv8a

gdk_clang_ndk_arm64-v8a-debug:
  extends: .ndk_release
  when: manual
  script:
    - mkdir gdk-android-jni
    - NUM_JOBS=16 ./tools/build.sh --buildtype=debug --install $PWD/gdk-android-jni --ndk arm64-v8a --external-deps-dir /prebld/armv8a

gdk_clang_ndk_x86:
  extends: .ndk_release
  when: manual # TODO remove
  script:
    - mkdir gdk-android-jni
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-android-jni --ndk x86 --external-deps-dir /prebld/x86

gdk_clang_ndk_x86_64:
  extends: .ndk_release
  script:
    - mkdir gdk-android-jni
    - NUM_JOBS=16 ./tools/build.sh --install $PWD/gdk-android-jni --ndk x86_64 --external-deps-dir /prebld/x86_64

test_rust:
  tags:
    - ga
  script:
    - source /root/.cargo/env
    - rustup override set 1.64.0
    - export WALLY_DIR=/prebld/gcc/libwally-core/build/lib/
    - export OPENSSL_DIR=/prebld/gcc/openssl/build 
    - export OPENSSL_STATIC=1
    - curl -L https://github.com/RCasatta/electrsd/releases/download/electrs_releases/electrs_linux_esplora_703c6a20d52b61a234a18812503bd754d448992a.gz | tar -xz
    - echo "6c62b280db4455a0bee1c60dcb7bb18f741313deb8aafdb7bad1bc2a3f4ff0b8  electrs" | sha256sum --check
    - chmod 755 electrs && mv electrs electrs_bitcoin
    - export ELECTRS_EXEC=$PWD/electrs_bitcoin
    - curl -L https://github.com/RCasatta/electrsd/releases/download/electrs_releases/electrs_linux_esplora_703c6a20d52b61a234a18812503bd754d448992a_liquid.gz | tar -xz
    - echo "47571e09fbc5bc25504e3b66ee47295cea9912182d42721c11d895183e5b6c6e  electrs" | sha256sum --check
    - chmod 755 electrs && mv electrs electrs_liquid
    - export ELECTRS_LIQUID_EXEC=$PWD/electrs_liquid
    - curl https://bitcoincore.org/bin/bitcoin-core-0.20.1/bitcoin-0.20.1-x86_64-linux-gnu.tar.gz | tar -xz bitcoin-0.20.1/bin/bitcoind
    - export BITCOIND_EXEC=$PWD/bitcoin-0.20.1/bin/bitcoind
    - curl -L https://github.com/ElementsProject/elements/releases/download/elements-0.21.0/elements-elements-0.21.0-x86_64-linux-gnu.tar.gz | tar -xz elements-elements-0.21.0/bin/elementsd
    - export ELEMENTSD_EXEC=$PWD/elements-elements-0.21.0/bin/elementsd
    - cd subprojects/gdk_rust
    - RUST_LOG=debug RUST_BACKTRACE=1 cargo test -- --nocapture

test_osx_clang:
  extends: .osx_test
  when: manual # TODO remove
  script:
    - cargo --version # TODO remove
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --clang

release_osx_ios:
  extends: .ios_release
  when: manual # TODO remove
  script:
    - cargo --version # TODO remove
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --iphone static --install $PWD/gdk-iphone

release_osx_ios_sim:
  extends: .ios_sim_release
  when: manual # TODO remove
  script:
    - cargo --version # TODO remove
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --iphonesim static --install $PWD/gdk-iphone-sim

release_osx_ios_debug:
  extends: .ios_release
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --iphone static --buildtype=debug --install $PWD/gdk-iphone

release_osx_ios_sim_debug:
  extends: .ios_sim_release
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ./tools/build.sh --iphonesim static --buildtype=debug --install $PWD/gdk-iphone-sim

test_osx_clang_ndk_armeabi-v7a:
  only:
    refs:
      - master
  extends: .osx_test
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ANDROID_NDK=/opt/android-ndk-r23b ./tools/build.sh --ndk armeabi-v7a

test_osx_clang_ndk_arm64-v8a:
  only:
    refs:
      - master
  extends: .osx_test
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ANDROID_NDK=/opt/ndroid-ndk-r23b ./tools/build.sh --ndk arm64-v8a

test_osx_clang_ndk_x86:
  only:
    refs:
      - master
  extends: .osx_test
  when: manual
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ANDROID_NDK=/opt/android-ndk-r23b ./tools/build.sh --ndk x86

test_osx_clang_ndk_x86_64:
  only:
    refs:
      - master
  when: manual
  extends: .osx_test
  script:
    - cd $CI_PROJECT_DIR
    - ./tools/clean.sh dirs
    - virtualenv venv && source venv/bin/activate && pip install -r ./tools/requirements.txt
    - NUM_JOBS=16 ANDROID_NDK=/opt/android-ndk-r23b ./tools/build.sh --ndk x86_64

test_windows_mingw_w64_cross:
  tags:
    - ga
  when: manual # TODO remove
  artifacts:
    expire_in: 1 hour
    when: on_success
    paths:
    - build-windows-mingw-w64/src/libgreenaddress*
  script:
    - NUM_JOBS=16 ./tools/build.sh --mingw-w64 --external-deps-dir /prebld/mingw-w64

apidocs:
  tags:
    - ga
  artifacts:
    expire_in: 14 days
    when: on_success
    paths:
    - apidocs.tar.gz
  script:
    - virtualenv -p python3 .venv
    - source .venv/bin/activate
    - pip3 install -r docs/requirements.txt
    - sphinx-build -b html -a -c docs/source docs/source docs/build/html
    - cd docs/build && tar czf ../../apidocs.tar.gz html/ && cd ../..
    - deactivate

package_release:
  tags:
    - garelease
  stage: deploy
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_SHORT_SHA"
    expire_in: 14 days
    paths:
    - $CI_PROJECT_DIR/gdk_dist
    when: on_success
  script:
    - cd $CI_PROJECT_DIR
    - mkdir gdk-android-symbols
    - mkdir gdk_dist
    #- find gdk-android-jni -name "*.syms" -type f -exec cp --parents {} gdk-android-symbols \;
    #- tar -czf gdk_dist/gdk-android-symbols.tar.gz gdk-android-symbols --remove-files
    #- find gdk-android-jni -name "*.a" -type f -delete
    #- find gdk-android-jni -name "*.syms" -type f -delete
    #- tar -czf gdk_dist/gdk-android-jni.tar.gz gdk-android-jni --remove-files
    #- tar -czf gdk_dist/gdk-iphone.tar.gz gdk-iphone --remove-files
    #- tar -czf gdk_dist/gdk-iphone-sim.tar.gz gdk-iphone-sim --remove-files
    - mv gdk-python/*whl gdk_dist/
    - cd gdk_dist
    - /opt/process_release
  dependencies:
  #- gdk_clang_ndk_armeabi-v7a
  - gdk_clang_ndk_arm64-v8a
  #- gdk_clang_ndk_x86
  - gdk_clang_ndk_x86_64
  - release_py3m_bullseye
  - release_py3m_ubuntu_18.04
  #- release_py3m_osx
  #- release_py3m_osx_m1
  #- release_osx_ios
  #- apidocs
  #- release_osx_ios_sim

cp_gcloud:
  image: blockstream/gcloud-docker-tf:1.1.7
  tags:
    - ga
  stage: publish
  script:
    - echo gs://green-gdk-builds/$CI_PROJECT_NAME-$CI_COMMIT_SHA
    - TMPF=$(mktemp) || exit 1
    - echo $GCLOUD_PUSH_KEY > $TMPF
    - export GOOGLE_APPLICATION_CREDENTIALS=$TMPF
    - gcloud auth activate-service-account --key-file=$TMPF
    - gsutil cp -r $CI_PROJECT_DIR/gdk_dist gs://green-gdk-builds/$CI_PROJECT_NAME-$CI_COMMIT_SHA
  dependencies:
  - package_release

cp_gcloud_master:
  image: blockstream/gcloud-docker-tf:1.1.7
  tags:
    - ga
  stage: publish
  only:
    refs:
      - master
  script:
    - TMPF=$(mktemp) || exit 1
    - echo $GCLOUD_PUSH_KEY > $TMPF
    - export GOOGLE_APPLICATION_CREDENTIALS=$TMPF
    - gcloud auth activate-service-account --key-file=$TMPF
    - gsutil rm -r gs://green-gdk-builds/gdk-master || echo fail # avoid failing when dir does not exist
    - gsutil cp -r $CI_PROJECT_DIR/gdk_dist gs://green-gdk-builds/gdk-master
  dependencies:
  - package_release

