[package]
name = "vls-protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
serde_bolt = { version = "0.2", default-features = false }
bolt-derive = { path = "../bolt-derive" }
log = "0.4"

[dev-dependencies]
regex = "1.5"
hex = "0.4"

[features]
std = ["serde_bolt/std"]
